pipeline {
    agent {
        docker {
            image 'node:6-alpine' 
            args '-p 3000:3000' 
        }
    }
    stages {
	stage('Build install stage') {
	    steps {
		echo '##### Build Install #####'
	    }
	}
        stage('Build') { 
            steps {
                sh 'npm install'
		echo 'Finish build install' 
            }
        }
    }
}
